-- Run in a Snowflake worksheet as ACCOUNTADMIN.
-- This role can run the app's three SELECT queries but cannot change data.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DATATHON_APP_ROLE
  COMMENT = 'Read-only role for the Food System Resilience Streamlit app';

GRANT USAGE ON WAREHOUSE FAOSTAT_WH TO ROLE DATATHON_APP_ROLE;
GRANT USAGE ON DATABASE FAOSTAT_DB TO ROLE DATATHON_APP_ROLE;

GRANT USAGE ON SCHEMA FAOSTAT_DB.ANALYTICS TO ROLE DATATHON_APP_ROLE;
GRANT USAGE ON SCHEMA FAOSTAT_DB.CLEAN TO ROLE DATATHON_APP_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FAOSTAT_DB.ANALYTICS
  TO ROLE DATATHON_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FAOSTAT_DB.CLEAN
  TO ROLE DATATHON_APP_ROLE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA FAOSTAT_DB.ANALYTICS
  TO ROLE DATATHON_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FAOSTAT_DB.CLEAN
  TO ROLE DATATHON_APP_ROLE;

GRANT ROLE DATATHON_APP_ROLE TO USER JRAPSON;

-- After running the grants, create a short-lived programmatic access token
-- restricted to DATATHON_APP_ROLE. Snowflake displays the token secret once.
-- Store that token only in Streamlit Community Cloud's Secrets field.
--
-- ALTER USER ADD PROGRAMMATIC ACCESS TOKEN DATATHON_STREAMLIT
--   ROLE_RESTRICTION = 'DATATHON_APP_ROLE'
--   DAYS_TO_EXPIRY = 30
--   MINS_TO_BYPASS_NETWORK_POLICY_REQUIREMENT = 30
--   COMMENT = 'Streamlit Community Cloud deployment for Datathon 2026';
