-- Add a trend-adjusted production shock to the resilience analysis.
-- Run after 15_build_resilience_analysis.sql has been run at least once.
--
-- Method:
--   1. Fit a country-specific linear trend over T-5 through T-1.
--   2. Require at least four observed pre-event years.
--   3. Predict the production index for T and T+1.
--   4. Report the worse percentage deviation from those two predictions.

USE WAREHOUSE FAOSTAT_WH;
USE DATABASE FAOSTAT_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.VW_EVENT_PRODUCTION_RESILIENCE_BASE AS
WITH event_windows AS (
  SELECT
    E.ISO3,
    E.AREA_CODE_M49,
    E.COUNTRY,
    E.FAOSTAT_AREA,
    E.EVENT_YEAR,
    E.EVENT_TYPES,
    E.TOTAL_FOCUS_EVENTS,
    E.DROUGHT_EVENTS,
    E.WILDFIRE_EVENTS,
    E.EXTREME_TEMPERATURE_EVENTS,
    E.FLOOD_EVENTS,
    E.STORM_EVENTS,
    E.TOTAL_AFFECTED_REPORTED,
    E.TOTAL_DEATHS_REPORTED,
    E.TOTAL_DAMAGE_ADJUSTED_000_USD,
    COUNT_IF(P.YEAR BETWEEN E.EVENT_YEAR - 3 AND E.EVENT_YEAR - 1) AS BASELINE_YEAR_COUNT,
    AVG(IFF(P.YEAR BETWEEN E.EVENT_YEAR - 3 AND E.EVENT_YEAR - 1, P.FOOD_PRODUCTION_INDEX, NULL)) AS BASELINE_INDEX,
    COUNT_IF(P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR - 1) AS TREND_YEAR_COUNT,
    REGR_SLOPE(
      IFF(P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR - 1, P.FOOD_PRODUCTION_INDEX, NULL),
      IFF(P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR - 1, P.YEAR, NULL)
    ) AS PRE_EVENT_TREND_SLOPE,
    REGR_INTERCEPT(
      IFF(P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR - 1, P.FOOD_PRODUCTION_INDEX, NULL),
      IFF(P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR - 1, P.YEAR, NULL)
    ) AS PRE_EVENT_TREND_INTERCEPT,
    MAX(IFF(P.YEAR = E.EVENT_YEAR, P.FOOD_PRODUCTION_INDEX, NULL)) AS EVENT_YEAR_INDEX,
    MAX(IFF(P.YEAR = E.EVENT_YEAR + 1, P.FOOD_PRODUCTION_INDEX, NULL)) AS YEAR_1_INDEX,
    MAX(IFF(P.YEAR = E.EVENT_YEAR + 2, P.FOOD_PRODUCTION_INDEX, NULL)) AS YEAR_2_INDEX,
    MAX(IFF(P.YEAR = E.EVENT_YEAR + 3, P.FOOD_PRODUCTION_INDEX, NULL)) AS YEAR_3_INDEX,
    MIN(IFF(P.YEAR BETWEEN E.EVENT_YEAR AND E.EVENT_YEAR + 1, P.FOOD_PRODUCTION_INDEX, NULL)) AS WORST_INDEX_T_TO_T1,
    (SELECT MAX(YEAR) FROM ANALYTICS.VW_FOOD_PRODUCTION_YEAR) AS MAX_PRODUCTION_YEAR
  FROM ANALYTICS.VW_CLIMATE_EVENTS_COUNTRY_YEAR E
  LEFT JOIN ANALYTICS.VW_FOOD_PRODUCTION_YEAR P
    ON P.AREA_CODE_M49 = E.AREA_CODE_M49
   AND P.YEAR BETWEEN E.EVENT_YEAR - 5 AND E.EVENT_YEAR + 3
  GROUP BY
    E.ISO3, E.AREA_CODE_M49, E.COUNTRY, E.FAOSTAT_AREA, E.EVENT_YEAR,
    E.EVENT_TYPES, E.TOTAL_FOCUS_EVENTS, E.DROUGHT_EVENTS, E.WILDFIRE_EVENTS,
    E.EXTREME_TEMPERATURE_EVENTS, E.FLOOD_EVENTS, E.STORM_EVENTS,
    E.TOTAL_AFFECTED_REPORTED, E.TOTAL_DEATHS_REPORTED,
    E.TOTAL_DAMAGE_ADJUSTED_000_USD
),
expected_values AS (
  SELECT
    *,
    IFF(
      TREND_YEAR_COUNT >= 4,
      PRE_EVENT_TREND_INTERCEPT + PRE_EVENT_TREND_SLOPE * EVENT_YEAR,
      NULL
    ) AS EXPECTED_EVENT_YEAR_INDEX,
    IFF(
      TREND_YEAR_COUNT >= 4,
      PRE_EVENT_TREND_INTERCEPT + PRE_EVENT_TREND_SLOPE * (EVENT_YEAR + 1),
      NULL
    ) AS EXPECTED_YEAR_1_INDEX
  FROM event_windows
),
metrics AS (
  SELECT
    *,
    100 * DIV0(EVENT_YEAR_INDEX - BASELINE_INDEX, BASELINE_INDEX) AS EVENT_YEAR_CHANGE_PERCENT,
    100 * DIV0(WORST_INDEX_T_TO_T1 - BASELINE_INDEX, BASELINE_INDEX) AS WORST_CHANGE_PERCENT_T_TO_T1,
    IFF(
      EXPECTED_EVENT_YEAR_INDEX > 0,
      100 * DIV0(EVENT_YEAR_INDEX - EXPECTED_EVENT_YEAR_INDEX, EXPECTED_EVENT_YEAR_INDEX),
      NULL
    ) AS EVENT_YEAR_DETRENDED_CHANGE_PERCENT,
    IFF(
      EXPECTED_YEAR_1_INDEX > 0 AND YEAR_1_INDEX IS NOT NULL,
      100 * DIV0(YEAR_1_INDEX - EXPECTED_YEAR_1_INDEX, EXPECTED_YEAR_1_INDEX),
      NULL
    ) AS YEAR_1_DETRENDED_CHANGE_PERCENT,
    LEAST_IGNORE_NULLS(
      IFF(
        EXPECTED_EVENT_YEAR_INDEX > 0,
        100 * DIV0(EVENT_YEAR_INDEX - EXPECTED_EVENT_YEAR_INDEX, EXPECTED_EVENT_YEAR_INDEX),
        NULL
      ),
      IFF(
        EXPECTED_YEAR_1_INDEX > 0 AND YEAR_1_INDEX IS NOT NULL,
        100 * DIV0(YEAR_1_INDEX - EXPECTED_YEAR_1_INDEX, EXPECTED_YEAR_1_INDEX),
        NULL
      )
    ) AS WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1,
    EVENT_YEAR <= MAX_PRODUCTION_YEAR - 3 AS HAS_FULL_3_YEAR_FOLLOWUP,
    CASE
      WHEN BASELINE_YEAR_COUNT < 2 OR BASELINE_INDEX IS NULL OR EVENT_YEAR_INDEX IS NULL THEN NULL
      WHEN EVENT_YEAR_INDEX >= 0.95 * BASELINE_INDEX THEN 0
      WHEN YEAR_1_INDEX >= 0.95 * BASELINE_INDEX THEN 1
      WHEN YEAR_2_INDEX >= 0.95 * BASELINE_INDEX THEN 2
      WHEN YEAR_3_INDEX >= 0.95 * BASELINE_INDEX THEN 3
      ELSE NULL
    END AS RECOVERY_YEARS
  FROM expected_values
)
SELECT
  *,
  CASE
    WHEN BASELINE_YEAR_COUNT < 2 OR BASELINE_INDEX IS NULL OR EVENT_YEAR_INDEX IS NULL THEN 'INSUFFICIENT_PRODUCTION_DATA'
    WHEN RECOVERY_YEARS = 0 THEN 'MAINTAINED'
    WHEN RECOVERY_YEARS IS NOT NULL THEN 'RECOVERED'
    WHEN NOT HAS_FULL_3_YEAR_FOLLOWUP THEN 'FOLLOW_UP_INCOMPLETE'
    ELSE 'NOT_RECOVERED_WITHIN_3_YEARS'
  END AS RECOVERY_STATUS,
  CASE
    WHEN BASELINE_YEAR_COUNT < 2 OR EVENT_YEAR_INDEX IS NULL THEN 'INSUFFICIENT_DATA'
    WHEN RECOVERY_YEARS = 0 THEN 'HIGH_RESILIENCE'
    WHEN EVENT_YEAR_CHANGE_PERCENT >= -10 AND RECOVERY_YEARS <= 1 THEN 'HIGH_RESILIENCE'
    WHEN RECOVERY_YEARS <= 3 THEN 'MODERATE_RESILIENCE'
    WHEN NOT HAS_FULL_3_YEAR_FOLLOWUP THEN 'PENDING_FOLLOW_UP'
    ELSE 'LOW_RESILIENCE'
  END AS RESILIENCE_CATEGORY
FROM metrics;

CREATE OR REPLACE VIEW ANALYTICS.VW_EVENT_PRODUCTION_RESILIENCE AS
SELECT
  R.*,
  V.YEAR AS VULNERABILITY_DATA_YEAR,
  V.FOOD_INSECURITY_PERCENT,
  V.UNDERNOURISHMENT_PERCENT,
  V.FOOD_INSECURITY_IS_UPPER_BOUND,
  V.UNDERNOURISHMENT_IS_UPPER_BOUND,
  COALESCE(V.FOOD_INSECURITY_PERCENT, V.UNDERNOURISHMENT_PERCENT) AS VULNERABILITY_PERCENT,
  IFF(V.FOOD_INSECURITY_PERCENT IS NOT NULL, 'MODERATE_OR_SEVERE_FOOD_INSECURITY_3YR_AVG',
      IFF(V.UNDERNOURISHMENT_PERCENT IS NOT NULL, 'UNDERNOURISHMENT_3YR_AVG_FALLBACK', NULL)) AS VULNERABILITY_MEASURE,
  CASE
    WHEN COALESCE(V.FOOD_INSECURITY_PERCENT, V.UNDERNOURISHMENT_PERCENT) IS NULL THEN 'UNKNOWN'
    WHEN COALESCE(V.FOOD_INSECURITY_PERCENT, V.UNDERNOURISHMENT_PERCENT) >= 25 THEN 'HIGH'
    WHEN COALESCE(V.FOOD_INSECURITY_PERCENT, V.UNDERNOURISHMENT_PERCENT) >= 10 THEN 'MODERATE'
    ELSE 'LOW'
  END AS FOOD_VULNERABILITY_CATEGORY
FROM ANALYTICS.VW_EVENT_PRODUCTION_RESILIENCE_BASE R
LEFT JOIN ANALYTICS.VW_FOOD_VULNERABILITY_YEAR V
  ON V.AREA_CODE_M49 = R.AREA_CODE_M49
 AND V.YEAR BETWEEN R.EVENT_YEAR - 2 AND R.EVENT_YEAR
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY R.ISO3, R.EVENT_YEAR
  ORDER BY V.YEAR DESC NULLS LAST
) = 1;

-- Coverage and comparison checks.
SELECT
  COUNT(*) AS COUNTRY_EVENT_YEARS,
  COUNT_IF(TREND_YEAR_COUNT >= 4) AS WITH_USABLE_PRE_EVENT_TREND,
  COUNT_IF(WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1 IS NOT NULL) AS WITH_DETRENDED_SHOCK,
  CORR(UNDERNOURISHMENT_PERCENT, WORST_CHANGE_PERCENT_T_TO_T1) AS RAW_CORRELATION,
  CORR(UNDERNOURISHMENT_PERCENT, WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1) AS DETRENDED_CORRELATION
FROM ANALYTICS.VW_EVENT_PRODUCTION_RESILIENCE;

SELECT
  ISO3,
  COUNTRY,
  EVENT_YEAR,
  EVENT_TYPES,
  TREND_YEAR_COUNT,
  PRE_EVENT_TREND_SLOPE,
  WORST_CHANGE_PERCENT_T_TO_T1,
  WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1,
  UNDERNOURISHMENT_PERCENT
FROM ANALYTICS.VW_EVENT_PRODUCTION_RESILIENCE
WHERE WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1 IS NOT NULL
ORDER BY ABS(WORST_DETRENDED_CHANGE_PERCENT_T_TO_T1) DESC
LIMIT 25;
